name: Changelog

on:
  workflow_dispatch:
  # Trigger analysis when pushing in master or pull requests,
  # and when creating a pull request.
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
      - name: Changelog
        uses: rhysd/changelog-from-release/action@78b335bb7d059f35ad04c5428d50711726feee50 # v3.9.1
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}